import type { Product, Supplier, User } from "./types"

export const SEED_USERS: User[] = [
  {
    id: "u-admin",
    name: "Doña Rosa",
    email: "admin@miabarrotes.mx",
    password: "admin123",
    role: "admin",
  },
  {
    id: "u-cliente",
    name: "Juan Pérez",
    email: "cliente@miabarrotes.mx",
    password: "cliente123",
    role: "cliente",
  },
]

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: "s-frescos",
    name: "Frutas y Verduras del Bajío",
    contact: "Ramón Aguilar",
    phone: "55 1234 5678",
    email: "ventas@frescosbajio.mx",
    category: "Frutas y Verduras",
    notes: "Entrega los lunes y jueves por la mañana.",
  },
  {
    id: "s-lacteos",
    name: "Lácteos La Vaquita",
    contact: "Patricia Méndez",
    phone: "55 8765 4321",
    email: "pedidos@lavaquita.mx",
    category: "Lácteos y Huevo",
    notes: "Producto refrigerado, requiere pago a 15 días.",
  },
  {
    id: "s-despensa",
    name: "Granos y Abarrotes González",
    contact: "Luis González",
    phone: "55 2468 1357",
    email: "contacto@granosgonzalez.mx",
    category: "Despensa",
    notes: "Mayoreo con descuento desde 10 bultos.",
  },
  {
    id: "s-bebidas",
    name: "Distribuidora de Bebidas El Sol",
    contact: "Carmen Ríos",
    phone: "55 1357 2468",
    email: "elsol@bebidas.mx",
    category: "Bebidas",
    notes: "Maneja botella retornable, recoge cascos vacíos.",
  },
]

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-manzanas",
    name: "Manzanas Rojas",
    description: "Manzanas frescas y crujientes, ideales para botana.",
    price: 38.5,
    unit: "kg",
    stock: 40,
    category: "Frutas y Verduras",
    image: "/products/manzanas.png",
  },
  {
    id: "p-platanos",
    name: "Plátano Tabasco",
    description: "Plátanos maduros, dulces y llenos de energía.",
    price: 19.9,
    unit: "kg",
    stock: 60,
    category: "Frutas y Verduras",
    image: "/products/platanos.png",
  },
  {
    id: "p-jitomate",
    name: "Jitomate Saladet",
    description: "Jitomate rojo perfecto para salsas y guisados.",
    price: 24.0,
    unit: "kg",
    stock: 35,
    category: "Frutas y Verduras",
    image: "/products/jitomate.png",
  },
  {
    id: "p-aguacate",
    name: "Aguacate Hass",
    description: "Aguacates cremosos, listos para tu guacamole.",
    price: 62.0,
    unit: "kg",
    stock: 25,
    category: "Frutas y Verduras",
    image: "/products/aguacate.png",
  },
  {
    id: "p-leche",
    name: "Leche Entera",
    description: "Leche fresca pasteurizada en botella de 1 litro.",
    price: 28.5,
    unit: "pza",
    stock: 50,
    category: "Lácteos y Huevo",
    image: "/products/leche.png",
  },
  {
    id: "p-huevos",
    name: "Huevo de Rancho",
    description: "Cartón con 12 huevos frescos de gallina libre.",
    price: 42.0,
    unit: "cartón",
    stock: 30,
    category: "Lácteos y Huevo",
    image: "/products/huevos.png",
  },
  {
    id: "p-frijol",
    name: "Frijol Negro",
    description: "Frijol negro seleccionado, bolsa de 1 kg.",
    price: 34.0,
    unit: "kg",
    stock: 45,
    category: "Despensa",
    image: "/products/frijol.png",
  },
  {
    id: "p-arroz",
    name: "Arroz Blanco",
    description: "Arroz de grano largo, ideal para todo platillo.",
    price: 26.0,
    unit: "kg",
    stock: 55,
    category: "Despensa",
    image: "/products/arroz.png",
  },
  {
    id: "p-cafe",
    name: "Café de Olla",
    description: "Café molido de Veracruz, aroma intenso de casa.",
    price: 89.0,
    unit: "500g",
    stock: 20,
    category: "Despensa",
    image: "/products/cafe.png",
  },
  {
    id: "p-refresco",
    name: "Refresco de Cola",
    description: "Refresco bien frío en botella de vidrio retornable.",
    price: 18.0,
    unit: "pza",
    stock: 70,
    category: "Bebidas",
    image: "/products/refresco.png",
  },
  {
    id: "p-tortillas",
    name: "Tortillas de Maíz",
    description: "Tortillas recién hechas a mano, paquete de 1 kg.",
    price: 22.0,
    unit: "kg",
    stock: 40,
    category: "Panadería",
    image: "/products/tortillas.png",
  },
]
